function results = resize227227Texture(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------

%Resize image to 227x227.
img = imresize(im,[227 227]);
%Convert to grayscale
img1 = rgb2gray(img);
%Detect local entropy
img2 = entropyfilt(img1);
%Rescale back to default pixel range
entropyim = rescale(img2);

results = entropyim;

%results.imgray = imgray;
%results.bw     = bw;

%--------------------------------------------------------------------------
